### PR TITLE
A few commands added

### PR DESCRIPTION
**Pull request by Proyecto513**
Hello

### CODE REVIEW

**Comment by Proyecto513** [comment]
What do you think about giving me write access ti your repo? Sounds like a good idea? :+1: ? :-1: ?

**Comment by Proyecto513** [comment]
Hello?

**Comment by vladimirnani** [comment]
ofc man. thanks for collaboration.

**Comment by vladimirnani** [comment]
claro que si amigo. gracias.

**Comment by Proyecto513** [comment]
Thanks :) good evening, my friend

**Pull request merged**
